#!/usr/bin/env bash

[[ $VERBOSE =~ true|True|On|on|1 ]] && set -x

set -aeu

RUN_TESTS=${RUN_TESTS:-1}
TEMPDIR=${TEMPDIR:-.}
RESIN=${RESIN:-0}

function finish() {
    rm -rf src/tests/venv
}
trap finish EXIT

function install_venv() {
    python3.9 -m venv src/tests/venv

    export PATH="$(pwd)/src/tests/venv/bin:${PATH}"

    pip install --upgrade pip setuptools wheel
    pip install --upgrade -r src/tests/requirements.txt
}

function run_tests() {
    install_venv

    nosetests --verbosity=2 src/tests
}

find . -name *.py -name requirements.txt -name run | xargs -I{} cp ../resin.io/{} {} || true

# run unit tests
if [[ "${RUN_TESTS}" == '1' ]]; then
    run_tests
fi
