#!/bin/sh

# copy source
for f in $(ls src/*.py); do
    [ -f ../resin.io/${f} ] && cp ../resin.io/${f} ../black.box/${f}
done

# copy tests
for f in $(ls src/tests/*.py); do
    [ -f ../resin.io/${f} ] && cp ../resin.io/${f} ../black.box/${f}
done

# run unit tests
if [[ "${RUN_TESTS}" == '1' ]]; then
    RESIN=1 TEMPDIR=. nosetests --verbosity=2 src/tests
    result=$?
    if [ ${result} -eq 1 ]; then
        exit ${result}
    fi
fi
exit 0
