#!/usr/bin/env bash

[[ $VERBOSE =~ true|True|On|on|1 ]] && set -x

set -aeu

SOURCE=${SOURCE:-../resin.io}
TARGET=${TARGET:-$(pwd)}

mkdir -p "${TARGET}/src/tests"

pushd "${SOURCE}"

find src \
  -name *.py -or \
  -name blackbox.plugin -or \
  -name run -or \
  -name requirements.txt | xargs -I{} cp -R "{}" "${TARGET}/{}"

popd
