#!/usr/bin/env bash

[[ $VERBOSE =~ true|True|On|on|1 ]] && set -x

set -aeu

RUN_TESTS=${RUN_TESTS:-1}
DATADIR=${DATADIR:-src/tests/data}
TEMPDIR=${TEMPDIR:-src/tests/temp}
DNS_SUB_DOMAIN=${DNS_SUB_DOMAIN:-blackbox}
RESIN=${RESIN:-0}

function finish() {
    rm -rf src/tests/venv "${DATADIR}" "${TEMPDIR}"
}
trap finish EXIT

function install_venv() {
    python3 -m venv src/tests/venv

    export PATH="$(pwd)/src/tests/venv/bin:${PATH}"

    pip install --upgrade pip setuptools wheel
    pip install --upgrade -r src/tests/requirements.txt
}

function run_tests() {
    install_venv

    mkdir -p "${DATADIR}" "${TEMPDIR}"

    touch ${DATADIR}/openvpn.{tcp,udp}.status

    nosetests --verbosity=2 src/tests
}

# run unit tests
if [[ $RUN_TESTS == 1 ]]; then
    run_tests
fi
